"""fix typo toal_money -> total_money

Revision ID: 18187bfc6833
Revises: 29db144a5044
Create Date: 2025-10-19 17:58:29.907305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18187bfc6833'
down_revision: Union[str, Sequence[str], None] = '29db144a5044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",             # tên bảng
        "toal_money",       # tên cột cũ
        new_column_name="total_money"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "total_money",
        new_column_name="toal_money"
    )
    # ### end Alembic commands ###
