"""add total_money column to users

Revision ID: 29db144a5044
Revises: fdd3c575bac5
Create Date: 2025-10-19 17:18:23.848076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29db144a5044'
down_revision: Union[str, Sequence[str], None] = 'fdd3c575bac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_money', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_money')
    # ### end Alembic commands ###
